# Generated by Django 5.2.3 on 2026-02-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Penggiling', 'Penggiling'), ('Pencacah', 'Pencacah'), ('Daur Ulang', 'Daur Ulang'), ('Penghancur', 'Penghancur'), ('Pelletizer', 'Pelletizer'), ('Kompak', 'Kompak'), ('Lainnya', 'Lainnya')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('specs', models.JSONField(default=list, help_text='List of specifications')),
                ('rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
