# Generated by Django 5.0 on 2026-02-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mesin', 'Mesin'), ('Alat', 'Alat'), ('Produk', 'Produk'), ('Bahan Baku', 'Bahan Baku'), ('Aksesoris', 'Aksesoris'), ('Lainnya', 'Lainnya')], default='Produk', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=list, help_text='List of specifications'),
        ),
    ]
