# Generated by Django 5.0 on 2026-02-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Pending', 'Pending'), ('Ditolak', 'Ditolak')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('Individu', 'Individu'), ('UMKM', 'UMKM'), ('Organisasi', 'Organisasi')], default='Pengumpul', max_length=50),
        ),
    ]
