# Generated by Django 5.2.3 on 2026-02-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(help_text='e.g. 4 minggu', max_length=50)),
                ('level', models.CharField(choices=[('Pemula', 'Pemula'), ('Menengah', 'Menengah'), ('Lanjutan', 'Lanjutan')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('features', models.JSONField(default=list, help_text='List of features')),
                ('type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('students_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
