# Generated by Django 5.0 on 2026-03-01 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_module_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='status',
            field=models.CharField(choices=[('process', 'Process'), ('berhasil', 'Berhasil')], default='process', max_length=20),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
