# Generated by Django 5.0 on 2026-03-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseregistration_status_courseregistration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='generated_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
