# Generated by Django 5.0 on 2026-02-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WastePickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('waste_type', models.CharField(choices=[('Plastik', 'Plastik'), ('Kertas/Kardus', 'Kertas/Kardus'), ('Logam', 'Logam'), ('Kaca', 'Kaca'), ('Elektronik', 'Elektronik'), ('Organik', 'Organik'), ('B3 (Bahan Berbahaya)', 'B3 (Bahan Berbahaya)'), ('Campuran', 'Campuran')], max_length=50)),
                ('estimated_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('confirmed', 'Dikonfirmasi'), ('in_progress', 'Dalam Proses'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_pickups', to='partners.partner')),
            ],
        ),
    ]
