# Generated by Django 5.0 on 2026-02-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_pickups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastepickup',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
