# Generated by Django 5.2.3 on 2026-02-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_author_article_excerpt_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Scheduled', 'Scheduled')], default='Draft', max_length=20),
        ),
    ]
